### PR TITLE
fix CMS tab name

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by xini** [comment]
That's for version 3 of https://github.com/fromholdio/silverstripe-superlinker-menus. 
See https://github.com/fromholdio/silverstripe-superlinker-menus/blob/2.0.2/src/Model/MenuItem.php#L101 vs https://github.com/fromholdio/silverstripe-superlinker-menus/blob/master/src/Model/MenuItem.php#L95.

**Comment by dizzystuff** [comment]
@xini I've tagged a new version ^3.0.0 and updated composer with superlinker-menus ^2.0.0 as min requirement.

**Comment by xini** [comment]
Thanks. Now fromholdio/silverstripe-superlinker-megamenus 2.0.0 requires fromholdio/silverstripe-elemental-group ^1.0.0, which doesn't include the new fix...

**Comment by dizzystuff** [comment]
@xini boom

**Comment by xini** [comment]
Thanks!

**Pull request merged**
